#!/bin/bash

## Local Backup Script for Borg Backup

export BORG_REPO='/borg'
export BORG_PASSPHRASE='<passphrase>'
export SENDGRID_API_KEY='<apikey>'
LOG_NAME="local-backup.log"
LOG_PATH=/var/log/borg-backup/local

# If the backup succeeds, send a success message through SendGrid and then prune the last backup
if borg create -v --stats ::$(hostname)-$(date +"%d-%b-%Y") /files >> /$LOG_PATH/$LOG_NAME 2>&1 ; then
  curl --request POST \
    --url https://api.sendgrid.com/v3/mail/send \
    --header "Authorization: Bearer $SENDGRID_API_KEY" \
    --header 'Content-Type: application/json' \
    --data '{"personalizations": [{"to": [{"email": "<to-email>"}]}],"from": {"email": "<from-email>"},"subject": "Success - Local Backup on '$(date +'%d-%b-%Y')'","content": [{"type": "text/plain", "value": "Your local backup on '$(date +'%d-%b-%Y')' was successful. \n The backup is called: '$(hostname)-$(date +'%d-%b-%Y')' "}]}'
	
  # Prune extra backups
  borg prune --prefix $(hostname)- --keep-daily=1

# If the backup fails, then send a failure message through SendGrid
 
else
curl --request POST \
  --url https://api.sendgrid.com/v3/mail/send \
  --header "Authorization: Bearer $SENDGRID_API_KEY" \
  --header 'Content-Type: application/json' \
  --data '{"personalizations": [{"to": [{"email": "<to-email>"}]}],"from": {"email": "<from-email>"},"subject": "Failure - Local Backup on '$(date +'%d-%b-%Y')'","content": [{"type": "text/plain", "value": "Your local backup on '$(date +'%d-%b-%Y')' failed."}]}'
fi
